# Generated by Django 3.1 on 2020-11-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_savedgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgame',
            name='player_color',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
