# Generated by Django 3.1 on 2020-11-14 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess', '0004_savedgame_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgame',
            name='enemy_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemy_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedgame',
            name='result',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedgame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
