# Generated by Django 3.1 on 2020-11-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_auto_20201114_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgame',
            name='mode',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
